// Country data credit: https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes

export interface Country {
  name: string;
  code: string;
  alpha_3: string;
  country_code: string;
  iso_3166_2: string;
  region: string;
  sub_region: string;
  intermediate_region: string;
  region_code: string;
  sub_region_code: string;
  intermediate_region_code: string;
  slug?: string;
}

export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES_WITH_SLUG.find((c) => c.code.toLowerCase() === code.toLowerCase());
}

export function getCountryName(code: string): string {
  const country = getCountryByCode(code);
  return country ? country.name : code;
}

export function toSlug(value: string) {
  return value
    .toLowerCase()
    .normalize('NFD') // handle Å, É, etc.
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

const COUNTRIES: Country[] = [
  {
    name: 'Afghanistan',
    code: 'AF',
    alpha_3: 'AFG',
    country_code: '004',
    iso_3166_2: 'ISO 3166-2:AF',
    region: 'Asia',
    sub_region: 'Southern Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '034',
    intermediate_region_code: '',
  },
  {
    name: 'Åland Islands',
    code: 'AX',
    alpha_3: 'ALA',
    country_code: '248',
    iso_3166_2: 'ISO 3166-2:AX',
    region: 'Europe',
    sub_region: 'Northern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '154',
    intermediate_region_code: '',
  },
  {
    name: 'Albania',
    code: 'AL',
    alpha_3: 'ALB',
    country_code: '008',
    iso_3166_2: 'ISO 3166-2:AL',
    region: 'Europe',
    sub_region: 'Southern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '039',
    intermediate_region_code: '',
  },
  {
    name: 'Algeria',
    code: 'DZ',
    alpha_3: 'DZA',
    country_code: '012',
    iso_3166_2: 'ISO 3166-2:DZ',
    region: 'Africa',
    sub_region: 'Northern Africa',
    intermediate_region: '',
    region_code: '002',
    sub_region_code: '015',
    intermediate_region_code: '',
  },
  {
    name: 'American Samoa',
    code: 'AS',
    alpha_3: 'ASM',
    country_code: '016',
    iso_3166_2: 'ISO 3166-2:AS',
    region: 'Oceania',
    sub_region: 'Polynesia',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '061',
    intermediate_region_code: '',
  },
  {
    name: 'Andorra',
    code: 'AD',
    alpha_3: 'AND',
    country_code: '020',
    iso_3166_2: 'ISO 3166-2:AD',
    region: 'Europe',
    sub_region: 'Southern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '039',
    intermediate_region_code: '',
  },
  {
    name: 'Angola',
    code: 'AO',
    alpha_3: 'AGO',
    country_code: '024',
    iso_3166_2: 'ISO 3166-2:AO',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Middle Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '017',
  },
  {
    name: 'Anguilla',
    code: 'AI',
    alpha_3: 'AIA',
    country_code: '660',
    iso_3166_2: 'ISO 3166-2:AI',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Antarctica',
    code: 'AQ',
    alpha_3: 'ATA',
    country_code: '010',
    iso_3166_2: 'ISO 3166-2:AQ',
    region: '',
    sub_region: '',
    intermediate_region: '',
    region_code: '',
    sub_region_code: '',
    intermediate_region_code: '',
  },
  {
    name: 'Antigua and Barbuda',
    code: 'AG',
    alpha_3: 'ATG',
    country_code: '028',
    iso_3166_2: 'ISO 3166-2:AG',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Argentina',
    code: 'AR',
    alpha_3: 'ARG',
    country_code: '032',
    iso_3166_2: 'ISO 3166-2:AR',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'South America',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '005',
  },
  {
    name: 'Armenia',
    code: 'AM',
    alpha_3: 'ARM',
    country_code: '051',
    iso_3166_2: 'ISO 3166-2:AM',
    region: 'Asia',
    sub_region: 'Western Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '145',
    intermediate_region_code: '',
  },
  {
    name: 'Aruba',
    code: 'AW',
    alpha_3: 'ABW',
    country_code: '533',
    iso_3166_2: 'ISO 3166-2:AW',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Australia',
    code: 'AU',
    alpha_3: 'AUS',
    country_code: '036',
    iso_3166_2: 'ISO 3166-2:AU',
    region: 'Oceania',
    sub_region: 'Australia and New Zealand',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '053',
    intermediate_region_code: '',
  },
  {
    name: 'Austria',
    code: 'AT',
    alpha_3: 'AUT',
    country_code: '040',
    iso_3166_2: 'ISO 3166-2:AT',
    region: 'Europe',
    sub_region: 'Western Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '155',
    intermediate_region_code: '',
  },
  {
    name: 'Azerbaijan',
    code: 'AZ',
    alpha_3: 'AZE',
    country_code: '031',
    iso_3166_2: 'ISO 3166-2:AZ',
    region: 'Asia',
    sub_region: 'Western Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '145',
    intermediate_region_code: '',
  },
  {
    name: 'Bahamas',
    code: 'BS',
    alpha_3: 'BHS',
    country_code: '044',
    iso_3166_2: 'ISO 3166-2:BS',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Bahrain',
    code: 'BH',
    alpha_3: 'BHR',
    country_code: '048',
    iso_3166_2: 'ISO 3166-2:BH',
    region: 'Asia',
    sub_region: 'Western Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '145',
    intermediate_region_code: '',
  },
  {
    name: 'Bangladesh',
    code: 'BD',
    alpha_3: 'BGD',
    country_code: '050',
    iso_3166_2: 'ISO 3166-2:BD',
    region: 'Asia',
    sub_region: 'Southern Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '034',
    intermediate_region_code: '',
  },
  {
    name: 'Barbados',
    code: 'BB',
    alpha_3: 'BRB',
    country_code: '052',
    iso_3166_2: 'ISO 3166-2:BB',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Belarus',
    code: 'BY',
    alpha_3: 'BLR',
    country_code: '112',
    iso_3166_2: 'ISO 3166-2:BY',
    region: 'Europe',
    sub_region: 'Eastern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '151',
    intermediate_region_code: '',
  },
  {
    name: 'Belgium',
    code: 'BE',
    alpha_3: 'BEL',
    country_code: '056',
    iso_3166_2: 'ISO 3166-2:BE',
    region: 'Europe',
    sub_region: 'Western Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '155',
    intermediate_region_code: '',
  },
  {
    name: 'Belize',
    code: 'BZ',
    alpha_3: 'BLZ',
    country_code: '084',
    iso_3166_2: 'ISO 3166-2:BZ',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Central America',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '013',
  },
  {
    name: 'Benin',
    code: 'BJ',
    alpha_3: 'BEN',
    country_code: '204',
    iso_3166_2: 'ISO 3166-2:BJ',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Western Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '011',
  },
  {
    name: 'Bermuda',
    code: 'BM',
    alpha_3: 'BMU',
    country_code: '060',
    iso_3166_2: 'ISO 3166-2:BM',
    region: 'Americas',
    sub_region: 'Northern America',
    intermediate_region: '',
    region_code: '019',
    sub_region_code: '021',
    intermediate_region_code: '',
  },
  {
    name: 'Bhutan',
    code: 'BT',
    alpha_3: 'BTN',
    country_code: '064',
    iso_3166_2: 'ISO 3166-2:BT',
    region: 'Asia',
    sub_region: 'Southern Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '034',
    intermediate_region_code: '',
  },
  {
    name: 'Bolivia, Plurinational State of',
    code: 'BO',
    alpha_3: 'BOL',
    country_code: '068',
    iso_3166_2: 'ISO 3166-2:BO',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'South America',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '005',
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    code: 'BQ',
    alpha_3: 'BES',
    country_code: '535',
    iso_3166_2: 'ISO 3166-2:BQ',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Bosnia and Herzegovina',
    code: 'BA',
    alpha_3: 'BIH',
    country_code: '070',
    iso_3166_2: 'ISO 3166-2:BA',
    region: 'Europe',
    sub_region: 'Southern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '039',
    intermediate_region_code: '',
  },
  {
    name: 'Botswana',
    code: 'BW',
    alpha_3: 'BWA',
    country_code: '072',
    iso_3166_2: 'ISO 3166-2:BW',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Southern Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '018',
  },
  {
    name: 'Bouvet Island',
    code: 'BV',
    alpha_3: 'BVT',
    country_code: '074',
    iso_3166_2: 'ISO 3166-2:BV',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'South America',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '005',
  },
  {
    name: 'Brazil',
    code: 'BR',
    alpha_3: 'BRA',
    country_code: '076',
    iso_3166_2: 'ISO 3166-2:BR',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'South America',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '005',
  },
  {
    name: 'British Indian Ocean Territory',
    code: 'IO',
    alpha_3: 'IOT',
    country_code: '086',
    iso_3166_2: 'ISO 3166-2:IO',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Eastern Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '014',
  },
  {
    name: 'Brunei Darussalam',
    code: 'BN',
    alpha_3: 'BRN',
    country_code: '096',
    iso_3166_2: 'ISO 3166-2:BN',
    region: 'Asia',
    sub_region: 'South-eastern Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '035',
    intermediate_region_code: '',
  },
  {
    name: 'Bulgaria',
    code: 'BG',
    alpha_3: 'BGR',
    country_code: '100',
    iso_3166_2: 'ISO 3166-2:BG',
    region: 'Europe',
    sub_region: 'Eastern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '151',
    intermediate_region_code: '',
  },
  {
    name: 'Burkina Faso',
    code: 'BF',
    alpha_3: 'BFA',
    country_code: '854',
    iso_3166_2: 'ISO 3166-2:BF',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Western Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '011',
  },
  {
    name: 'Burundi',
    code: 'BI',
    alpha_3: 'BDI',
    country_code: '108',
    iso_3166_2: 'ISO 3166-2:BI',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Eastern Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '014',
  },
  {
    name: 'Cabo Verde',
    code: 'CV',
    alpha_3: 'CPV',
    country_code: '132',
    iso_3166_2: 'ISO 3166-2:CV',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Western Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '011',
  },
  {
    name: 'Cambodia',
    code: 'KH',
    alpha_3: 'KHM',
    country_code: '116',
    iso_3166_2: 'ISO 3166-2:KH',
    region: 'Asia',
    sub_region: 'South-eastern Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '035',
    intermediate_region_code: '',
  },
  {
    name: 'Cameroon',
    code: 'CM',
    alpha_3: 'CMR',
    country_code: '120',
    iso_3166_2: 'ISO 3166-2:CM',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Middle Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '017',
  },
  {
    name: 'Canada',
    code: 'CA',
    alpha_3: 'CAN',
    country_code: '124',
    iso_3166_2: 'ISO 3166-2:CA',
    region: 'Americas',
    sub_region: 'Northern America',
    intermediate_region: '',
    region_code: '019',
    sub_region_code: '021',
    intermediate_region_code: '',
  },
  {
    name: 'Cayman Islands',
    code: 'KY',
    alpha_3: 'CYM',
    country_code: '136',
    iso_3166_2: 'ISO 3166-2:KY',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Central African Republic',
    code: 'CF',
    alpha_3: 'CAF',
    country_code: '140',
    iso_3166_2: 'ISO 3166-2:CF',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Middle Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '017',
  },
  {
    name: 'Chad',
    code: 'TD',
    alpha_3: 'TCD',
    country_code: '148',
    iso_3166_2: 'ISO 3166-2:TD',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Middle Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '017',
  },
  {
    name: 'Chile',
    code: 'CL',
    alpha_3: 'CHL',
    country_code: '152',
    iso_3166_2: 'ISO 3166-2:CL',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'South America',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '005',
  },
  {
    name: 'China',
    code: 'CN',
    alpha_3: 'CHN',
    country_code: '156',
    iso_3166_2: 'ISO 3166-2:CN',
    region: 'Asia',
    sub_region: 'Eastern Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '030',
    intermediate_region_code: '',
  },
  {
    name: 'Christmas Island',
    code: 'CX',
    alpha_3: 'CXR',
    country_code: '162',
    iso_3166_2: 'ISO 3166-2:CX',
    region: 'Oceania',
    sub_region: 'Australia and New Zealand',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '053',
    intermediate_region_code: '',
  },
  {
    name: 'Cocos (Keeling) Islands',
    code: 'CC',
    alpha_3: 'CCK',
    country_code: '166',
    iso_3166_2: 'ISO 3166-2:CC',
    region: 'Oceania',
    sub_region: 'Australia and New Zealand',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '053',
    intermediate_region_code: '',
  },
  {
    name: 'Colombia',
    code: 'CO',
    alpha_3: 'COL',
    country_code: '170',
    iso_3166_2: 'ISO 3166-2:CO',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'South America',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '005',
  },
  {
    name: 'Comoros',
    code: 'KM',
    alpha_3: 'COM',
    country_code: '174',
    iso_3166_2: 'ISO 3166-2:KM',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Eastern Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '014',
  },
  {
    name: 'Congo',
    code: 'CG',
    alpha_3: 'COG',
    country_code: '178',
    iso_3166_2: 'ISO 3166-2:CG',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Middle Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '017',
  },
  {
    name: 'Congo, Democratic Republic of the',
    code: 'CD',
    alpha_3: 'COD',
    country_code: '180',
    iso_3166_2: 'ISO 3166-2:CD',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Middle Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '017',
  },
  {
    name: 'Cook Islands',
    code: 'CK',
    alpha_3: 'COK',
    country_code: '184',
    iso_3166_2: 'ISO 3166-2:CK',
    region: 'Oceania',
    sub_region: 'Polynesia',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '061',
    intermediate_region_code: '',
  },
  {
    name: 'Costa Rica',
    code: 'CR',
    alpha_3: 'CRI',
    country_code: '188',
    iso_3166_2: 'ISO 3166-2:CR',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Central America',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '013',
  },
  {
    name: "Côte d'Ivoire",
    code: 'CI',
    alpha_3: 'CIV',
    country_code: '384',
    iso_3166_2: 'ISO 3166-2:CI',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Western Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '011',
  },
  {
    name: 'Croatia',
    code: 'HR',
    alpha_3: 'HRV',
    country_code: '191',
    iso_3166_2: 'ISO 3166-2:HR',
    region: 'Europe',
    sub_region: 'Southern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '039',
    intermediate_region_code: '',
  },
  {
    name: 'Cuba',
    code: 'CU',
    alpha_3: 'CUB',
    country_code: '192',
    iso_3166_2: 'ISO 3166-2:CU',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Curaçao',
    code: 'CW',
    alpha_3: 'CUW',
    country_code: '531',
    iso_3166_2: 'ISO 3166-2:CW',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Cyprus',
    code: 'CY',
    alpha_3: 'CYP',
    country_code: '196',
    iso_3166_2: 'ISO 3166-2:CY',
    region: 'Asia',
    sub_region: 'Western Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '145',
    intermediate_region_code: '',
  },
  {
    name: 'Czechia',
    code: 'CZ',
    alpha_3: 'CZE',
    country_code: '203',
    iso_3166_2: 'ISO 3166-2:CZ',
    region: 'Europe',
    sub_region: 'Eastern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '151',
    intermediate_region_code: '',
  },
  {
    name: 'Denmark',
    code: 'DK',
    alpha_3: 'DNK',
    country_code: '208',
    iso_3166_2: 'ISO 3166-2:DK',
    region: 'Europe',
    sub_region: 'Northern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '154',
    intermediate_region_code: '',
  },
  {
    name: 'Djibouti',
    code: 'DJ',
    alpha_3: 'DJI',
    country_code: '262',
    iso_3166_2: 'ISO 3166-2:DJ',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Eastern Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '014',
  },
  {
    name: 'Dominica',
    code: 'DM',
    alpha_3: 'DMA',
    country_code: '212',
    iso_3166_2: 'ISO 3166-2:DM',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Dominican Republic',
    code: 'DO',
    alpha_3: 'DOM',
    country_code: '214',
    iso_3166_2: 'ISO 3166-2:DO',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Ecuador',
    code: 'EC',
    alpha_3: 'ECU',
    country_code: '218',
    iso_3166_2: 'ISO 3166-2:EC',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'South America',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '005',
  },
  {
    name: 'Egypt',
    code: 'EG',
    alpha_3: 'EGY',
    country_code: '818',
    iso_3166_2: 'ISO 3166-2:EG',
    region: 'Africa',
    sub_region: 'Northern Africa',
    intermediate_region: '',
    region_code: '002',
    sub_region_code: '015',
    intermediate_region_code: '',
  },
  {
    name: 'El Salvador',
    code: 'SV',
    alpha_3: 'SLV',
    country_code: '222',
    iso_3166_2: 'ISO 3166-2:SV',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Central America',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '013',
  },
  {
    name: 'Equatorial Guinea',
    code: 'GQ',
    alpha_3: 'GNQ',
    country_code: '226',
    iso_3166_2: 'ISO 3166-2:GQ',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Middle Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '017',
  },
  {
    name: 'Eritrea',
    code: 'ER',
    alpha_3: 'ERI',
    country_code: '232',
    iso_3166_2: 'ISO 3166-2:ER',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Eastern Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '014',
  },
  {
    name: 'Estonia',
    code: 'EE',
    alpha_3: 'EST',
    country_code: '233',
    iso_3166_2: 'ISO 3166-2:EE',
    region: 'Europe',
    sub_region: 'Northern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '154',
    intermediate_region_code: '',
  },
  {
    name: 'Eswatini',
    code: 'SZ',
    alpha_3: 'SWZ',
    country_code: '748',
    iso_3166_2: 'ISO 3166-2:SZ',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Southern Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '018',
  },
  {
    name: 'Ethiopia',
    code: 'ET',
    alpha_3: 'ETH',
    country_code: '231',
    iso_3166_2: 'ISO 3166-2:ET',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Eastern Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '014',
  },
  {
    name: 'Falkland Islands (Malvinas)',
    code: 'FK',
    alpha_3: 'FLK',
    country_code: '238',
    iso_3166_2: 'ISO 3166-2:FK',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'South America',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '005',
  },
  {
    name: 'Faroe Islands',
    code: 'FO',
    alpha_3: 'FRO',
    country_code: '234',
    iso_3166_2: 'ISO 3166-2:FO',
    region: 'Europe',
    sub_region: 'Northern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '154',
    intermediate_region_code: '',
  },
  {
    name: 'Fiji',
    code: 'FJ',
    alpha_3: 'FJI',
    country_code: '242',
    iso_3166_2: 'ISO 3166-2:FJ',
    region: 'Oceania',
    sub_region: 'Melanesia',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '054',
    intermediate_region_code: '',
  },
  {
    name: 'Finland',
    code: 'FI',
    alpha_3: 'FIN',
    country_code: '246',
    iso_3166_2: 'ISO 3166-2:FI',
    region: 'Europe',
    sub_region: 'Northern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '154',
    intermediate_region_code: '',
  },
  {
    name: 'France',
    code: 'FR',
    alpha_3: 'FRA',
    country_code: '250',
    iso_3166_2: 'ISO 3166-2:FR',
    region: 'Europe',
    sub_region: 'Western Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '155',
    intermediate_region_code: '',
  },
  {
    name: 'French Guiana',
    code: 'GF',
    alpha_3: 'GUF',
    country_code: '254',
    iso_3166_2: 'ISO 3166-2:GF',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'South America',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '005',
  },
  {
    name: 'French Polynesia',
    code: 'PF',
    alpha_3: 'PYF',
    country_code: '258',
    iso_3166_2: 'ISO 3166-2:PF',
    region: 'Oceania',
    sub_region: 'Polynesia',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '061',
    intermediate_region_code: '',
  },
  {
    name: 'French Southern Territories',
    code: 'TF',
    alpha_3: 'ATF',
    country_code: '260',
    iso_3166_2: 'ISO 3166-2:TF',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Eastern Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '014',
  },
  {
    name: 'Gabon',
    code: 'GA',
    alpha_3: 'GAB',
    country_code: '266',
    iso_3166_2: 'ISO 3166-2:GA',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Middle Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '017',
  },
  {
    name: 'Gambia',
    code: 'GM',
    alpha_3: 'GMB',
    country_code: '270',
    iso_3166_2: 'ISO 3166-2:GM',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Western Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '011',
  },
  {
    name: 'Georgia',
    code: 'GE',
    alpha_3: 'GEO',
    country_code: '268',
    iso_3166_2: 'ISO 3166-2:GE',
    region: 'Asia',
    sub_region: 'Western Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '145',
    intermediate_region_code: '',
  },
  {
    name: 'Germany',
    code: 'DE',
    alpha_3: 'DEU',
    country_code: '276',
    iso_3166_2: 'ISO 3166-2:DE',
    region: 'Europe',
    sub_region: 'Western Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '155',
    intermediate_region_code: '',
  },
  {
    name: 'Ghana',
    code: 'GH',
    alpha_3: 'GHA',
    country_code: '288',
    iso_3166_2: 'ISO 3166-2:GH',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Western Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '011',
  },
  {
    name: 'Gibraltar',
    code: 'GI',
    alpha_3: 'GIB',
    country_code: '292',
    iso_3166_2: 'ISO 3166-2:GI',
    region: 'Europe',
    sub_region: 'Southern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '039',
    intermediate_region_code: '',
  },
  {
    name: 'Greece',
    code: 'GR',
    alpha_3: 'GRC',
    country_code: '300',
    iso_3166_2: 'ISO 3166-2:GR',
    region: 'Europe',
    sub_region: 'Southern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '039',
    intermediate_region_code: '',
  },
  {
    name: 'Greenland',
    code: 'GL',
    alpha_3: 'GRL',
    country_code: '304',
    iso_3166_2: 'ISO 3166-2:GL',
    region: 'Americas',
    sub_region: 'Northern America',
    intermediate_region: '',
    region_code: '019',
    sub_region_code: '021',
    intermediate_region_code: '',
  },
  {
    name: 'Grenada',
    code: 'GD',
    alpha_3: 'GRD',
    country_code: '308',
    iso_3166_2: 'ISO 3166-2:GD',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Guadeloupe',
    code: 'GP',
    alpha_3: 'GLP',
    country_code: '312',
    iso_3166_2: 'ISO 3166-2:GP',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Guam',
    code: 'GU',
    alpha_3: 'GUM',
    country_code: '316',
    iso_3166_2: 'ISO 3166-2:GU',
    region: 'Oceania',
    sub_region: 'Micronesia',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '057',
    intermediate_region_code: '',
  },
  {
    name: 'Guatemala',
    code: 'GT',
    alpha_3: 'GTM',
    country_code: '320',
    iso_3166_2: 'ISO 3166-2:GT',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Central America',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '013',
  },
  {
    name: 'Guernsey',
    code: 'GG',
    alpha_3: 'GGY',
    country_code: '831',
    iso_3166_2: 'ISO 3166-2:GG',
    region: 'Europe',
    sub_region: 'Northern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '154',
    intermediate_region_code: '',
  },
  {
    name: 'Guinea',
    code: 'GN',
    alpha_3: 'GIN',
    country_code: '324',
    iso_3166_2: 'ISO 3166-2:GN',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Western Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '011',
  },
  {
    name: 'Guinea-Bissau',
    code: 'GW',
    alpha_3: 'GNB',
    country_code: '624',
    iso_3166_2: 'ISO 3166-2:GW',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Western Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '011',
  },
  {
    name: 'Guyana',
    code: 'GY',
    alpha_3: 'GUY',
    country_code: '328',
    iso_3166_2: 'ISO 3166-2:GY',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'South America',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '005',
  },
  {
    name: 'Haiti',
    code: 'HT',
    alpha_3: 'HTI',
    country_code: '332',
    iso_3166_2: 'ISO 3166-2:HT',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Heard Island and McDonald Islands',
    code: 'HM',
    alpha_3: 'HMD',
    country_code: '334',
    iso_3166_2: 'ISO 3166-2:HM',
    region: 'Oceania',
    sub_region: 'Australia and New Zealand',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '053',
    intermediate_region_code: '',
  },
  {
    name: 'Holy See',
    code: 'VA',
    alpha_3: 'VAT',
    country_code: '336',
    iso_3166_2: 'ISO 3166-2:VA',
    region: 'Europe',
    sub_region: 'Southern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '039',
    intermediate_region_code: '',
  },
  {
    name: 'Honduras',
    code: 'HN',
    alpha_3: 'HND',
    country_code: '340',
    iso_3166_2: 'ISO 3166-2:HN',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Central America',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '013',
  },
  {
    name: 'Hong Kong',
    code: 'HK',
    alpha_3: 'HKG',
    country_code: '344',
    iso_3166_2: 'ISO 3166-2:HK',
    region: 'Asia',
    sub_region: 'Eastern Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '030',
    intermediate_region_code: '',
  },
  {
    name: 'Hungary',
    code: 'HU',
    alpha_3: 'HUN',
    country_code: '348',
    iso_3166_2: 'ISO 3166-2:HU',
    region: 'Europe',
    sub_region: 'Eastern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '151',
    intermediate_region_code: '',
  },
  {
    name: 'Iceland',
    code: 'IS',
    alpha_3: 'ISL',
    country_code: '352',
    iso_3166_2: 'ISO 3166-2:IS',
    region: 'Europe',
    sub_region: 'Northern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '154',
    intermediate_region_code: '',
  },
  {
    name: 'India',
    code: 'IN',
    alpha_3: 'IND',
    country_code: '356',
    iso_3166_2: 'ISO 3166-2:IN',
    region: 'Asia',
    sub_region: 'Southern Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '034',
    intermediate_region_code: '',
  },
  {
    name: 'Indonesia',
    code: 'ID',
    alpha_3: 'IDN',
    country_code: '360',
    iso_3166_2: 'ISO 3166-2:ID',
    region: 'Asia',
    sub_region: 'South-eastern Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '035',
    intermediate_region_code: '',
  },
  {
    name: 'Iran, Islamic Republic of',
    code: 'IR',
    alpha_3: 'IRN',
    country_code: '364',
    iso_3166_2: 'ISO 3166-2:IR',
    region: 'Asia',
    sub_region: 'Southern Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '034',
    intermediate_region_code: '',
  },
  {
    name: 'Iraq',
    code: 'IQ',
    alpha_3: 'IRQ',
    country_code: '368',
    iso_3166_2: 'ISO 3166-2:IQ',
    region: 'Asia',
    sub_region: 'Western Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '145',
    intermediate_region_code: '',
  },
  {
    name: 'Ireland',
    code: 'IE',
    alpha_3: 'IRL',
    country_code: '372',
    iso_3166_2: 'ISO 3166-2:IE',
    region: 'Europe',
    sub_region: 'Northern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '154',
    intermediate_region_code: '',
  },
  {
    name: 'Isle of Man',
    code: 'IM',
    alpha_3: 'IMN',
    country_code: '833',
    iso_3166_2: 'ISO 3166-2:IM',
    region: 'Europe',
    sub_region: 'Northern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '154',
    intermediate_region_code: '',
  },
  {
    name: 'Israel',
    code: 'IL',
    alpha_3: 'ISR',
    country_code: '376',
    iso_3166_2: 'ISO 3166-2:IL',
    region: 'Asia',
    sub_region: 'Western Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '145',
    intermediate_region_code: '',
  },
  {
    name: 'Italy',
    code: 'IT',
    alpha_3: 'ITA',
    country_code: '380',
    iso_3166_2: 'ISO 3166-2:IT',
    region: 'Europe',
    sub_region: 'Southern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '039',
    intermediate_region_code: '',
  },
  {
    name: 'Jamaica',
    code: 'JM',
    alpha_3: 'JAM',
    country_code: '388',
    iso_3166_2: 'ISO 3166-2:JM',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Japan',
    code: 'JP',
    alpha_3: 'JPN',
    country_code: '392',
    iso_3166_2: 'ISO 3166-2:JP',
    region: 'Asia',
    sub_region: 'Eastern Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '030',
    intermediate_region_code: '',
  },
  {
    name: 'Jersey',
    code: 'JE',
    alpha_3: 'JEY',
    country_code: '832',
    iso_3166_2: 'ISO 3166-2:JE',
    region: 'Europe',
    sub_region: 'Northern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '154',
    intermediate_region_code: '',
  },
  {
    name: 'Jordan',
    code: 'JO',
    alpha_3: 'JOR',
    country_code: '400',
    iso_3166_2: 'ISO 3166-2:JO',
    region: 'Asia',
    sub_region: 'Western Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '145',
    intermediate_region_code: '',
  },
  {
    name: 'Kazakhstan',
    code: 'KZ',
    alpha_3: 'KAZ',
    country_code: '398',
    iso_3166_2: 'ISO 3166-2:KZ',
    region: 'Asia',
    sub_region: 'Central Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '143',
    intermediate_region_code: '',
  },
  {
    name: 'Kenya',
    code: 'KE',
    alpha_3: 'KEN',
    country_code: '404',
    iso_3166_2: 'ISO 3166-2:KE',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Eastern Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '014',
  },
  {
    name: 'Kiribati',
    code: 'KI',
    alpha_3: 'KIR',
    country_code: '296',
    iso_3166_2: 'ISO 3166-2:KI',
    region: 'Oceania',
    sub_region: 'Micronesia',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '057',
    intermediate_region_code: '',
  },
  {
    name: "Korea, Democratic People's Republic of",
    code: 'KP',
    alpha_3: 'PRK',
    country_code: '408',
    iso_3166_2: 'ISO 3166-2:KP',
    region: 'Asia',
    sub_region: 'Eastern Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '030',
    intermediate_region_code: '',
  },
  {
    name: 'Korea, Republic of',
    code: 'KR',
    alpha_3: 'KOR',
    country_code: '410',
    iso_3166_2: 'ISO 3166-2:KR',
    region: 'Asia',
    sub_region: 'Eastern Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '030',
    intermediate_region_code: '',
  },
  {
    name: 'Kuwait',
    code: 'KW',
    alpha_3: 'KWT',
    country_code: '414',
    iso_3166_2: 'ISO 3166-2:KW',
    region: 'Asia',
    sub_region: 'Western Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '145',
    intermediate_region_code: '',
  },
  {
    name: 'Kyrgyzstan',
    code: 'KG',
    alpha_3: 'KGZ',
    country_code: '417',
    iso_3166_2: 'ISO 3166-2:KG',
    region: 'Asia',
    sub_region: 'Central Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '143',
    intermediate_region_code: '',
  },
  {
    name: "Lao People's Democratic Republic",
    code: 'LA',
    alpha_3: 'LAO',
    country_code: '418',
    iso_3166_2: 'ISO 3166-2:LA',
    region: 'Asia',
    sub_region: 'South-eastern Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '035',
    intermediate_region_code: '',
  },
  {
    name: 'Latvia',
    code: 'LV',
    alpha_3: 'LVA',
    country_code: '428',
    iso_3166_2: 'ISO 3166-2:LV',
    region: 'Europe',
    sub_region: 'Northern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '154',
    intermediate_region_code: '',
  },
  {
    name: 'Lebanon',
    code: 'LB',
    alpha_3: 'LBN',
    country_code: '422',
    iso_3166_2: 'ISO 3166-2:LB',
    region: 'Asia',
    sub_region: 'Western Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '145',
    intermediate_region_code: '',
  },
  {
    name: 'Lesotho',
    code: 'LS',
    alpha_3: 'LSO',
    country_code: '426',
    iso_3166_2: 'ISO 3166-2:LS',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Southern Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '018',
  },
  {
    name: 'Liberia',
    code: 'LR',
    alpha_3: 'LBR',
    country_code: '430',
    iso_3166_2: 'ISO 3166-2:LR',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Western Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '011',
  },
  {
    name: 'Libya',
    code: 'LY',
    alpha_3: 'LBY',
    country_code: '434',
    iso_3166_2: 'ISO 3166-2:LY',
    region: 'Africa',
    sub_region: 'Northern Africa',
    intermediate_region: '',
    region_code: '002',
    sub_region_code: '015',
    intermediate_region_code: '',
  },
  {
    name: 'Liechtenstein',
    code: 'LI',
    alpha_3: 'LIE',
    country_code: '438',
    iso_3166_2: 'ISO 3166-2:LI',
    region: 'Europe',
    sub_region: 'Western Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '155',
    intermediate_region_code: '',
  },
  {
    name: 'Lithuania',
    code: 'LT',
    alpha_3: 'LTU',
    country_code: '440',
    iso_3166_2: 'ISO 3166-2:LT',
    region: 'Europe',
    sub_region: 'Northern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '154',
    intermediate_region_code: '',
  },
  {
    name: 'Luxembourg',
    code: 'LU',
    alpha_3: 'LUX',
    country_code: '442',
    iso_3166_2: 'ISO 3166-2:LU',
    region: 'Europe',
    sub_region: 'Western Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '155',
    intermediate_region_code: '',
  },
  {
    name: 'Macao',
    code: 'MO',
    alpha_3: 'MAC',
    country_code: '446',
    iso_3166_2: 'ISO 3166-2:MO',
    region: 'Asia',
    sub_region: 'Eastern Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '030',
    intermediate_region_code: '',
  },
  {
    name: 'Madagascar',
    code: 'MG',
    alpha_3: 'MDG',
    country_code: '450',
    iso_3166_2: 'ISO 3166-2:MG',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Eastern Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '014',
  },
  {
    name: 'Malawi',
    code: 'MW',
    alpha_3: 'MWI',
    country_code: '454',
    iso_3166_2: 'ISO 3166-2:MW',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Eastern Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '014',
  },
  {
    name: 'Malaysia',
    code: 'MY',
    alpha_3: 'MYS',
    country_code: '458',
    iso_3166_2: 'ISO 3166-2:MY',
    region: 'Asia',
    sub_region: 'South-eastern Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '035',
    intermediate_region_code: '',
  },
  {
    name: 'Maldives',
    code: 'MV',
    alpha_3: 'MDV',
    country_code: '462',
    iso_3166_2: 'ISO 3166-2:MV',
    region: 'Asia',
    sub_region: 'Southern Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '034',
    intermediate_region_code: '',
  },
  {
    name: 'Mali',
    code: 'ML',
    alpha_3: 'MLI',
    country_code: '466',
    iso_3166_2: 'ISO 3166-2:ML',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Western Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '011',
  },
  {
    name: 'Malta',
    code: 'MT',
    alpha_3: 'MLT',
    country_code: '470',
    iso_3166_2: 'ISO 3166-2:MT',
    region: 'Europe',
    sub_region: 'Southern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '039',
    intermediate_region_code: '',
  },
  {
    name: 'Marshall Islands',
    code: 'MH',
    alpha_3: 'MHL',
    country_code: '584',
    iso_3166_2: 'ISO 3166-2:MH',
    region: 'Oceania',
    sub_region: 'Micronesia',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '057',
    intermediate_region_code: '',
  },
  {
    name: 'Martinique',
    code: 'MQ',
    alpha_3: 'MTQ',
    country_code: '474',
    iso_3166_2: 'ISO 3166-2:MQ',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Mauritania',
    code: 'MR',
    alpha_3: 'MRT',
    country_code: '478',
    iso_3166_2: 'ISO 3166-2:MR',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Western Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '011',
  },
  {
    name: 'Mauritius',
    code: 'MU',
    alpha_3: 'MUS',
    country_code: '480',
    iso_3166_2: 'ISO 3166-2:MU',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Eastern Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '014',
  },
  {
    name: 'Mayotte',
    code: 'YT',
    alpha_3: 'MYT',
    country_code: '175',
    iso_3166_2: 'ISO 3166-2:YT',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Eastern Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '014',
  },
  {
    name: 'Mexico',
    code: 'MX',
    alpha_3: 'MEX',
    country_code: '484',
    iso_3166_2: 'ISO 3166-2:MX',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Central America',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '013',
  },
  {
    name: 'Micronesia, Federated States of',
    code: 'FM',
    alpha_3: 'FSM',
    country_code: '583',
    iso_3166_2: 'ISO 3166-2:FM',
    region: 'Oceania',
    sub_region: 'Micronesia',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '057',
    intermediate_region_code: '',
  },
  {
    name: 'Moldova, Republic of',
    code: 'MD',
    alpha_3: 'MDA',
    country_code: '498',
    iso_3166_2: 'ISO 3166-2:MD',
    region: 'Europe',
    sub_region: 'Eastern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '151',
    intermediate_region_code: '',
  },
  {
    name: 'Monaco',
    code: 'MC',
    alpha_3: 'MCO',
    country_code: '492',
    iso_3166_2: 'ISO 3166-2:MC',
    region: 'Europe',
    sub_region: 'Western Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '155',
    intermediate_region_code: '',
  },
  {
    name: 'Mongolia',
    code: 'MN',
    alpha_3: 'MNG',
    country_code: '496',
    iso_3166_2: 'ISO 3166-2:MN',
    region: 'Asia',
    sub_region: 'Eastern Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '030',
    intermediate_region_code: '',
  },
  {
    name: 'Montenegro',
    code: 'ME',
    alpha_3: 'MNE',
    country_code: '499',
    iso_3166_2: 'ISO 3166-2:ME',
    region: 'Europe',
    sub_region: 'Southern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '039',
    intermediate_region_code: '',
  },
  {
    name: 'Montserrat',
    code: 'MS',
    alpha_3: 'MSR',
    country_code: '500',
    iso_3166_2: 'ISO 3166-2:MS',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Morocco',
    code: 'MA',
    alpha_3: 'MAR',
    country_code: '504',
    iso_3166_2: 'ISO 3166-2:MA',
    region: 'Africa',
    sub_region: 'Northern Africa',
    intermediate_region: '',
    region_code: '002',
    sub_region_code: '015',
    intermediate_region_code: '',
  },
  {
    name: 'Mozambique',
    code: 'MZ',
    alpha_3: 'MOZ',
    country_code: '508',
    iso_3166_2: 'ISO 3166-2:MZ',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Eastern Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '014',
  },
  {
    name: 'Myanmar',
    code: 'MM',
    alpha_3: 'MMR',
    country_code: '104',
    iso_3166_2: 'ISO 3166-2:MM',
    region: 'Asia',
    sub_region: 'South-eastern Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '035',
    intermediate_region_code: '',
  },
  {
    name: 'Namibia',
    code: 'NA',
    alpha_3: 'NAM',
    country_code: '516',
    iso_3166_2: 'ISO 3166-2:NA',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Southern Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '018',
  },
  {
    name: 'Nauru',
    code: 'NR',
    alpha_3: 'NRU',
    country_code: '520',
    iso_3166_2: 'ISO 3166-2:NR',
    region: 'Oceania',
    sub_region: 'Micronesia',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '057',
    intermediate_region_code: '',
  },
  {
    name: 'Nepal',
    code: 'NP',
    alpha_3: 'NPL',
    country_code: '524',
    iso_3166_2: 'ISO 3166-2:NP',
    region: 'Asia',
    sub_region: 'Southern Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '034',
    intermediate_region_code: '',
  },
  {
    name: 'Netherlands, Kingdom of the',
    code: 'NL',
    alpha_3: 'NLD',
    country_code: '528',
    iso_3166_2: 'ISO 3166-2:NL',
    region: 'Europe',
    sub_region: 'Western Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '155',
    intermediate_region_code: '',
  },
  {
    name: 'New Caledonia',
    code: 'NC',
    alpha_3: 'NCL',
    country_code: '540',
    iso_3166_2: 'ISO 3166-2:NC',
    region: 'Oceania',
    sub_region: 'Melanesia',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '054',
    intermediate_region_code: '',
  },
  {
    name: 'New Zealand',
    code: 'NZ',
    alpha_3: 'NZL',
    country_code: '554',
    iso_3166_2: 'ISO 3166-2:NZ',
    region: 'Oceania',
    sub_region: 'Australia and New Zealand',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '053',
    intermediate_region_code: '',
  },
  {
    name: 'Nicaragua',
    code: 'NI',
    alpha_3: 'NIC',
    country_code: '558',
    iso_3166_2: 'ISO 3166-2:NI',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Central America',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '013',
  },
  {
    name: 'Niger',
    code: 'NE',
    alpha_3: 'NER',
    country_code: '562',
    iso_3166_2: 'ISO 3166-2:NE',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Western Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '011',
  },
  {
    name: 'Nigeria',
    code: 'NG',
    alpha_3: 'NGA',
    country_code: '566',
    iso_3166_2: 'ISO 3166-2:NG',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Western Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '011',
  },
  {
    name: 'Niue',
    code: 'NU',
    alpha_3: 'NIU',
    country_code: '570',
    iso_3166_2: 'ISO 3166-2:NU',
    region: 'Oceania',
    sub_region: 'Polynesia',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '061',
    intermediate_region_code: '',
  },
  {
    name: 'Norfolk Island',
    code: 'NF',
    alpha_3: 'NFK',
    country_code: '574',
    iso_3166_2: 'ISO 3166-2:NF',
    region: 'Oceania',
    sub_region: 'Australia and New Zealand',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '053',
    intermediate_region_code: '',
  },
  {
    name: 'North Macedonia',
    code: 'MK',
    alpha_3: 'MKD',
    country_code: '807',
    iso_3166_2: 'ISO 3166-2:MK',
    region: 'Europe',
    sub_region: 'Southern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '039',
    intermediate_region_code: '',
  },
  {
    name: 'Northern Mariana Islands',
    code: 'MP',
    alpha_3: 'MNP',
    country_code: '580',
    iso_3166_2: 'ISO 3166-2:MP',
    region: 'Oceania',
    sub_region: 'Micronesia',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '057',
    intermediate_region_code: '',
  },
  {
    name: 'Norway',
    code: 'NO',
    alpha_3: 'NOR',
    country_code: '578',
    iso_3166_2: 'ISO 3166-2:NO',
    region: 'Europe',
    sub_region: 'Northern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '154',
    intermediate_region_code: '',
  },
  {
    name: 'Oman',
    code: 'OM',
    alpha_3: 'OMN',
    country_code: '512',
    iso_3166_2: 'ISO 3166-2:OM',
    region: 'Asia',
    sub_region: 'Western Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '145',
    intermediate_region_code: '',
  },
  {
    name: 'Pakistan',
    code: 'PK',
    alpha_3: 'PAK',
    country_code: '586',
    iso_3166_2: 'ISO 3166-2:PK',
    region: 'Asia',
    sub_region: 'Southern Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '034',
    intermediate_region_code: '',
  },
  {
    name: 'Palau',
    code: 'PW',
    alpha_3: 'PLW',
    country_code: '585',
    iso_3166_2: 'ISO 3166-2:PW',
    region: 'Oceania',
    sub_region: 'Micronesia',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '057',
    intermediate_region_code: '',
  },
  {
    name: 'Palestine, State of',
    code: 'PS',
    alpha_3: 'PSE',
    country_code: '275',
    iso_3166_2: 'ISO 3166-2:PS',
    region: 'Asia',
    sub_region: 'Western Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '145',
    intermediate_region_code: '',
  },
  {
    name: 'Panama',
    code: 'PA',
    alpha_3: 'PAN',
    country_code: '591',
    iso_3166_2: 'ISO 3166-2:PA',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Central America',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '013',
  },
  {
    name: 'Papua New Guinea',
    code: 'PG',
    alpha_3: 'PNG',
    country_code: '598',
    iso_3166_2: 'ISO 3166-2:PG',
    region: 'Oceania',
    sub_region: 'Melanesia',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '054',
    intermediate_region_code: '',
  },
  {
    name: 'Paraguay',
    code: 'PY',
    alpha_3: 'PRY',
    country_code: '600',
    iso_3166_2: 'ISO 3166-2:PY',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'South America',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '005',
  },
  {
    name: 'Peru',
    code: 'PE',
    alpha_3: 'PER',
    country_code: '604',
    iso_3166_2: 'ISO 3166-2:PE',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'South America',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '005',
  },
  {
    name: 'Philippines',
    code: 'PH',
    alpha_3: 'PHL',
    country_code: '608',
    iso_3166_2: 'ISO 3166-2:PH',
    region: 'Asia',
    sub_region: 'South-eastern Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '035',
    intermediate_region_code: '',
  },
  {
    name: 'Pitcairn',
    code: 'PN',
    alpha_3: 'PCN',
    country_code: '612',
    iso_3166_2: 'ISO 3166-2:PN',
    region: 'Oceania',
    sub_region: 'Polynesia',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '061',
    intermediate_region_code: '',
  },
  {
    name: 'Poland',
    code: 'PL',
    alpha_3: 'POL',
    country_code: '616',
    iso_3166_2: 'ISO 3166-2:PL',
    region: 'Europe',
    sub_region: 'Eastern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '151',
    intermediate_region_code: '',
  },
  {
    name: 'Portugal',
    code: 'PT',
    alpha_3: 'PRT',
    country_code: '620',
    iso_3166_2: 'ISO 3166-2:PT',
    region: 'Europe',
    sub_region: 'Southern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '039',
    intermediate_region_code: '',
  },
  {
    name: 'Puerto Rico',
    code: 'PR',
    alpha_3: 'PRI',
    country_code: '630',
    iso_3166_2: 'ISO 3166-2:PR',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Qatar',
    code: 'QA',
    alpha_3: 'QAT',
    country_code: '634',
    iso_3166_2: 'ISO 3166-2:QA',
    region: 'Asia',
    sub_region: 'Western Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '145',
    intermediate_region_code: '',
  },
  {
    name: 'Réunion',
    code: 'RE',
    alpha_3: 'REU',
    country_code: '638',
    iso_3166_2: 'ISO 3166-2:RE',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Eastern Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '014',
  },
  {
    name: 'Romania',
    code: 'RO',
    alpha_3: 'ROU',
    country_code: '642',
    iso_3166_2: 'ISO 3166-2:RO',
    region: 'Europe',
    sub_region: 'Eastern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '151',
    intermediate_region_code: '',
  },
  {
    name: 'Russian Federation',
    code: 'RU',
    alpha_3: 'RUS',
    country_code: '643',
    iso_3166_2: 'ISO 3166-2:RU',
    region: 'Europe',
    sub_region: 'Eastern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '151',
    intermediate_region_code: '',
  },
  {
    name: 'Rwanda',
    code: 'RW',
    alpha_3: 'RWA',
    country_code: '646',
    iso_3166_2: 'ISO 3166-2:RW',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Eastern Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '014',
  },
  {
    name: 'Saint Barthélemy',
    code: 'BL',
    alpha_3: 'BLM',
    country_code: '652',
    iso_3166_2: 'ISO 3166-2:BL',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    code: 'SH',
    alpha_3: 'SHN',
    country_code: '654',
    iso_3166_2: 'ISO 3166-2:SH',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Western Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '011',
  },
  {
    name: 'Saint Kitts and Nevis',
    code: 'KN',
    alpha_3: 'KNA',
    country_code: '659',
    iso_3166_2: 'ISO 3166-2:KN',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Saint Lucia',
    code: 'LC',
    alpha_3: 'LCA',
    country_code: '662',
    iso_3166_2: 'ISO 3166-2:LC',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Saint Martin (French part)',
    code: 'MF',
    alpha_3: 'MAF',
    country_code: '663',
    iso_3166_2: 'ISO 3166-2:MF',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Saint Pierre and Miquelon',
    code: 'PM',
    alpha_3: 'SPM',
    country_code: '666',
    iso_3166_2: 'ISO 3166-2:PM',
    region: 'Americas',
    sub_region: 'Northern America',
    intermediate_region: '',
    region_code: '019',
    sub_region_code: '021',
    intermediate_region_code: '',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    code: 'VC',
    alpha_3: 'VCT',
    country_code: '670',
    iso_3166_2: 'ISO 3166-2:VC',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Samoa',
    code: 'WS',
    alpha_3: 'WSM',
    country_code: '882',
    iso_3166_2: 'ISO 3166-2:WS',
    region: 'Oceania',
    sub_region: 'Polynesia',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '061',
    intermediate_region_code: '',
  },
  {
    name: 'San Marino',
    code: 'SM',
    alpha_3: 'SMR',
    country_code: '674',
    iso_3166_2: 'ISO 3166-2:SM',
    region: 'Europe',
    sub_region: 'Southern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '039',
    intermediate_region_code: '',
  },
  {
    name: 'Sao Tome and Principe',
    code: 'ST',
    alpha_3: 'STP',
    country_code: '678',
    iso_3166_2: 'ISO 3166-2:ST',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Middle Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '017',
  },
  {
    name: 'Saudi Arabia',
    code: 'SA',
    alpha_3: 'SAU',
    country_code: '682',
    iso_3166_2: 'ISO 3166-2:SA',
    region: 'Asia',
    sub_region: 'Western Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '145',
    intermediate_region_code: '',
  },
  {
    name: 'Senegal',
    code: 'SN',
    alpha_3: 'SEN',
    country_code: '686',
    iso_3166_2: 'ISO 3166-2:SN',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Western Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '011',
  },
  {
    name: 'Serbia',
    code: 'RS',
    alpha_3: 'SRB',
    country_code: '688',
    iso_3166_2: 'ISO 3166-2:RS',
    region: 'Europe',
    sub_region: 'Southern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '039',
    intermediate_region_code: '',
  },
  {
    name: 'Seychelles',
    code: 'SC',
    alpha_3: 'SYC',
    country_code: '690',
    iso_3166_2: 'ISO 3166-2:SC',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Eastern Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '014',
  },
  {
    name: 'Sierra Leone',
    code: 'SL',
    alpha_3: 'SLE',
    country_code: '694',
    iso_3166_2: 'ISO 3166-2:SL',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Western Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '011',
  },
  {
    name: 'Singapore',
    code: 'SG',
    alpha_3: 'SGP',
    country_code: '702',
    iso_3166_2: 'ISO 3166-2:SG',
    region: 'Asia',
    sub_region: 'South-eastern Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '035',
    intermediate_region_code: '',
  },
  {
    name: 'Sint Maarten (Dutch part)',
    code: 'SX',
    alpha_3: 'SXM',
    country_code: '534',
    iso_3166_2: 'ISO 3166-2:SX',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Slovakia',
    code: 'SK',
    alpha_3: 'SVK',
    country_code: '703',
    iso_3166_2: 'ISO 3166-2:SK',
    region: 'Europe',
    sub_region: 'Eastern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '151',
    intermediate_region_code: '',
  },
  {
    name: 'Slovenia',
    code: 'SI',
    alpha_3: 'SVN',
    country_code: '705',
    iso_3166_2: 'ISO 3166-2:SI',
    region: 'Europe',
    sub_region: 'Southern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '039',
    intermediate_region_code: '',
  },
  {
    name: 'Solomon Islands',
    code: 'SB',
    alpha_3: 'SLB',
    country_code: '090',
    iso_3166_2: 'ISO 3166-2:SB',
    region: 'Oceania',
    sub_region: 'Melanesia',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '054',
    intermediate_region_code: '',
  },
  {
    name: 'Somalia',
    code: 'SO',
    alpha_3: 'SOM',
    country_code: '706',
    iso_3166_2: 'ISO 3166-2:SO',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Eastern Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '014',
  },
  {
    name: 'South Africa',
    code: 'ZA',
    alpha_3: 'ZAF',
    country_code: '710',
    iso_3166_2: 'ISO 3166-2:ZA',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Southern Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '018',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    code: 'GS',
    alpha_3: 'SGS',
    country_code: '239',
    iso_3166_2: 'ISO 3166-2:GS',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'South America',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '005',
  },
  {
    name: 'South Sudan',
    code: 'SS',
    alpha_3: 'SSD',
    country_code: '728',
    iso_3166_2: 'ISO 3166-2:SS',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Eastern Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '014',
  },
  {
    name: 'Spain',
    code: 'ES',
    alpha_3: 'ESP',
    country_code: '724',
    iso_3166_2: 'ISO 3166-2:ES',
    region: 'Europe',
    sub_region: 'Southern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '039',
    intermediate_region_code: '',
  },
  {
    name: 'Sri Lanka',
    code: 'LK',
    alpha_3: 'LKA',
    country_code: '144',
    iso_3166_2: 'ISO 3166-2:LK',
    region: 'Asia',
    sub_region: 'Southern Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '034',
    intermediate_region_code: '',
  },
  {
    name: 'Sudan',
    code: 'SD',
    alpha_3: 'SDN',
    country_code: '729',
    iso_3166_2: 'ISO 3166-2:SD',
    region: 'Africa',
    sub_region: 'Northern Africa',
    intermediate_region: '',
    region_code: '002',
    sub_region_code: '015',
    intermediate_region_code: '',
  },
  {
    name: 'Suriname',
    code: 'SR',
    alpha_3: 'SUR',
    country_code: '740',
    iso_3166_2: 'ISO 3166-2:SR',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'South America',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '005',
  },
  {
    name: 'Svalbard and Jan Mayen',
    code: 'SJ',
    alpha_3: 'SJM',
    country_code: '744',
    iso_3166_2: 'ISO 3166-2:SJ',
    region: 'Europe',
    sub_region: 'Northern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '154',
    intermediate_region_code: '',
  },
  {
    name: 'Sweden',
    code: 'SE',
    alpha_3: 'SWE',
    country_code: '752',
    iso_3166_2: 'ISO 3166-2:SE',
    region: 'Europe',
    sub_region: 'Northern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '154',
    intermediate_region_code: '',
  },
  {
    name: 'Switzerland',
    code: 'CH',
    alpha_3: 'CHE',
    country_code: '756',
    iso_3166_2: 'ISO 3166-2:CH',
    region: 'Europe',
    sub_region: 'Western Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '155',
    intermediate_region_code: '',
  },
  {
    name: 'Syrian Arab Republic',
    code: 'SY',
    alpha_3: 'SYR',
    country_code: '760',
    iso_3166_2: 'ISO 3166-2:SY',
    region: 'Asia',
    sub_region: 'Western Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '145',
    intermediate_region_code: '',
  },
  {
    name: 'Taiwan',
    code: 'TW',
    alpha_3: 'TWN',
    country_code: '158',
    iso_3166_2: 'ISO 3166-2:TW',
    region: '',
    sub_region: '',
    intermediate_region: '',
    region_code: '',
    sub_region_code: '',
    intermediate_region_code: '',
  },
  {
    name: 'Tajikistan',
    code: 'TJ',
    alpha_3: 'TJK',
    country_code: '762',
    iso_3166_2: 'ISO 3166-2:TJ',
    region: 'Asia',
    sub_region: 'Central Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '143',
    intermediate_region_code: '',
  },
  {
    name: 'Tanzania, United Republic of',
    code: 'TZ',
    alpha_3: 'TZA',
    country_code: '834',
    iso_3166_2: 'ISO 3166-2:TZ',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Eastern Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '014',
  },
  {
    name: 'Thailand',
    code: 'TH',
    alpha_3: 'THA',
    country_code: '764',
    iso_3166_2: 'ISO 3166-2:TH',
    region: 'Asia',
    sub_region: 'South-eastern Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '035',
    intermediate_region_code: '',
  },
  {
    name: 'Timor-Leste',
    code: 'TL',
    alpha_3: 'TLS',
    country_code: '626',
    iso_3166_2: 'ISO 3166-2:TL',
    region: 'Asia',
    sub_region: 'South-eastern Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '035',
    intermediate_region_code: '',
  },
  {
    name: 'Togo',
    code: 'TG',
    alpha_3: 'TGO',
    country_code: '768',
    iso_3166_2: 'ISO 3166-2:TG',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Western Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '011',
  },
  {
    name: 'Tokelau',
    code: 'TK',
    alpha_3: 'TKL',
    country_code: '772',
    iso_3166_2: 'ISO 3166-2:TK',
    region: 'Oceania',
    sub_region: 'Polynesia',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '061',
    intermediate_region_code: '',
  },
  {
    name: 'Tonga',
    code: 'TO',
    alpha_3: 'TON',
    country_code: '776',
    iso_3166_2: 'ISO 3166-2:TO',
    region: 'Oceania',
    sub_region: 'Polynesia',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '061',
    intermediate_region_code: '',
  },
  {
    name: 'Trinidad and Tobago',
    code: 'TT',
    alpha_3: 'TTO',
    country_code: '780',
    iso_3166_2: 'ISO 3166-2:TT',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Tunisia',
    code: 'TN',
    alpha_3: 'TUN',
    country_code: '788',
    iso_3166_2: 'ISO 3166-2:TN',
    region: 'Africa',
    sub_region: 'Northern Africa',
    intermediate_region: '',
    region_code: '002',
    sub_region_code: '015',
    intermediate_region_code: '',
  },
  {
    name: 'Türkiye',
    code: 'TR',
    alpha_3: 'TUR',
    country_code: '792',
    iso_3166_2: 'ISO 3166-2:TR',
    region: 'Asia',
    sub_region: 'Western Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '145',
    intermediate_region_code: '',
  },
  {
    name: 'Turkmenistan',
    code: 'TM',
    alpha_3: 'TKM',
    country_code: '795',
    iso_3166_2: 'ISO 3166-2:TM',
    region: 'Asia',
    sub_region: 'Central Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '143',
    intermediate_region_code: '',
  },
  {
    name: 'Turks and Caicos Islands',
    code: 'TC',
    alpha_3: 'TCA',
    country_code: '796',
    iso_3166_2: 'ISO 3166-2:TC',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Tuvalu',
    code: 'TV',
    alpha_3: 'TUV',
    country_code: '798',
    iso_3166_2: 'ISO 3166-2:TV',
    region: 'Oceania',
    sub_region: 'Polynesia',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '061',
    intermediate_region_code: '',
  },
  {
    name: 'Uganda',
    code: 'UG',
    alpha_3: 'UGA',
    country_code: '800',
    iso_3166_2: 'ISO 3166-2:UG',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Eastern Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '014',
  },
  {
    name: 'Ukraine',
    code: 'UA',
    alpha_3: 'UKR',
    country_code: '804',
    iso_3166_2: 'ISO 3166-2:UA',
    region: 'Europe',
    sub_region: 'Eastern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '151',
    intermediate_region_code: '',
  },
  {
    name: 'United Arab Emirates',
    code: 'AE',
    alpha_3: 'ARE',
    country_code: '784',
    iso_3166_2: 'ISO 3166-2:AE',
    region: 'Asia',
    sub_region: 'Western Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '145',
    intermediate_region_code: '',
  },
  {
    name: 'United Kingdom',
    code: 'GB',
    alpha_3: 'GBR',
    country_code: '826',
    iso_3166_2: 'ISO 3166-2:GB',
    region: 'Europe',
    sub_region: 'Northern Europe',
    intermediate_region: '',
    region_code: '150',
    sub_region_code: '154',
    intermediate_region_code: '',
  },
  {
    name: 'United States of America',
    code: 'US',
    alpha_3: 'USA',
    country_code: '840',
    iso_3166_2: 'ISO 3166-2:US',
    region: 'Americas',
    sub_region: 'Northern America',
    intermediate_region: '',
    region_code: '019',
    sub_region_code: '021',
    intermediate_region_code: '',
  },
  {
    name: 'United States Minor Outlying Islands',
    code: 'UM',
    alpha_3: 'UMI',
    country_code: '581',
    iso_3166_2: 'ISO 3166-2:UM',
    region: 'Oceania',
    sub_region: 'Micronesia',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '057',
    intermediate_region_code: '',
  },
  {
    name: 'Uruguay',
    code: 'UY',
    alpha_3: 'URY',
    country_code: '858',
    iso_3166_2: 'ISO 3166-2:UY',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'South America',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '005',
  },
  {
    name: 'Uzbekistan',
    code: 'UZ',
    alpha_3: 'UZB',
    country_code: '860',
    iso_3166_2: 'ISO 3166-2:UZ',
    region: 'Asia',
    sub_region: 'Central Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '143',
    intermediate_region_code: '',
  },
  {
    name: 'Vanuatu',
    code: 'VU',
    alpha_3: 'VUT',
    country_code: '548',
    iso_3166_2: 'ISO 3166-2:VU',
    region: 'Oceania',
    sub_region: 'Melanesia',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '054',
    intermediate_region_code: '',
  },
  {
    name: 'Venezuela, Bolivarian Republic of',
    code: 'VE',
    alpha_3: 'VEN',
    country_code: '862',
    iso_3166_2: 'ISO 3166-2:VE',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'South America',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '005',
  },
  {
    name: 'Viet Nam',
    code: 'VN',
    alpha_3: 'VNM',
    country_code: '704',
    iso_3166_2: 'ISO 3166-2:VN',
    region: 'Asia',
    sub_region: 'South-eastern Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '035',
    intermediate_region_code: '',
  },
  {
    name: 'Virgin Islands (British)',
    code: 'VG',
    alpha_3: 'VGB',
    country_code: '092',
    iso_3166_2: 'ISO 3166-2:VG',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Virgin Islands (U.S.)',
    code: 'VI',
    alpha_3: 'VIR',
    country_code: '850',
    iso_3166_2: 'ISO 3166-2:VI',
    region: 'Americas',
    sub_region: 'Latin America and the Caribbean',
    intermediate_region: 'Caribbean',
    region_code: '019',
    sub_region_code: '419',
    intermediate_region_code: '029',
  },
  {
    name: 'Wallis and Futuna',
    code: 'WF',
    alpha_3: 'WLF',
    country_code: '876',
    iso_3166_2: 'ISO 3166-2:WF',
    region: 'Oceania',
    sub_region: 'Polynesia',
    intermediate_region: '',
    region_code: '009',
    sub_region_code: '061',
    intermediate_region_code: '',
  },
  {
    name: 'Western Sahara',
    code: 'EH',
    alpha_3: 'ESH',
    country_code: '732',
    iso_3166_2: 'ISO 3166-2:EH',
    region: 'Africa',
    sub_region: 'Northern Africa',
    intermediate_region: '',
    region_code: '002',
    sub_region_code: '015',
    intermediate_region_code: '',
  },
  {
    name: 'Yemen',
    code: 'YE',
    alpha_3: 'YEM',
    country_code: '887',
    iso_3166_2: 'ISO 3166-2:YE',
    region: 'Asia',
    sub_region: 'Western Asia',
    intermediate_region: '',
    region_code: '142',
    sub_region_code: '145',
    intermediate_region_code: '',
  },
  {
    name: 'Zambia',
    code: 'ZM',
    alpha_3: 'ZMB',
    country_code: '894',
    iso_3166_2: 'ISO 3166-2:ZM',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Eastern Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '014',
  },
  {
    name: 'Zimbabwe',
    code: 'ZW',
    alpha_3: 'ZWE',
    country_code: '716',
    iso_3166_2: 'ISO 3166-2:ZW',
    region: 'Africa',
    sub_region: 'Sub-Saharan Africa',
    intermediate_region: 'Eastern Africa',
    region_code: '002',
    sub_region_code: '202',
    intermediate_region_code: '014',
  },
];

export const COUNTRIES_WITH_SLUG: Country[] = COUNTRIES.map((c) => ({
  ...c,
  slug: toSlug(c.name),
}));

const countryBySlugMap: Record<string, Country> = Object.fromEntries(
  COUNTRIES_WITH_SLUG.map((c) => [c.slug!, c])
);

export function getCountryBySlug(slug: string): Country | undefined {
  return countryBySlugMap[toSlug(slug)];
}
